spring:
  application:
    name: Main


# H2 Database 설정
datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password:

# H2 Console 활성화
h2:
  console:
    enabled: true
    path: /h2-console

# JPA 설정
jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true

# DevTools 설정
devtools:
  restart:
    enabled: true
    additional-paths: src/main/java
    exclude: static/**,public/**,templates/**
    poll-interval: 2s
    quiet-period: 1s
  livereload:
    enabled: true

# 서버 포트 설정
server:
  port: 8080

# 로깅 설정
logging:
  level:
    com.example.demo: DEBUG
    org.springframework.boot.devtools: DEBUG
    org.springframework.web.servlet.resource: DEBUG

my:
  name: HanSeongDeok
  age: 29