spring:
  application:
    name: Main

  # H2 Database 설정
  # datasource:
  #   # url: jdbc:h2:mem:testdb
  #   url: jdbc:h2:file:./data/testdb
  #   driverClassName: org.h2.Driver
  #   username: sa
  #   password:

  # # H2 Console 활성화
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console

  # PostgreSQL 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234

  # JPA 설정
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # DevTools 설정
  devtools:
    restart:
      enabled: false

  # 서버 포트 설정
server:
  port: 8080

  # 로깅 설정
logging:
  level:
    com.example.demo: DEBUG
    org.springframework.boot.devtools: DEBUG
    org.springframework.web.servlet.resource: DEBUG

my:
  name: HanSeongDeok
  age: 29